{% set version = "0.7.0" %}

package:
  name: cargo-feature
  version: {{ version }}

source:
  url: https://github.com/Riey/cargo-feature/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5b88c1380f1bd6f3d7168137f08a6a534194d21254435a520c39a616398721f8

build:
  number: 1

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - cargo-feature --help

about:
  home: https://github.com/Riey/cargo-feature
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Cargo plugin to manage dependency features
  dev_url: https://github.com/Riey/cargo-feature

extra:
  recipe-maintainers:
    - '0xbe7a'
