github:
  branch_name: main
  tooling_branch_name: main
build_platform:
  osx_arm64: osx_64
conda_build:
  error_overlinking: true
provider:
  linux_aarch64: default
  linux_ppc64le: default
  win: azure
conda_forge_output_validation: true
test: native_and_emulated
